/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Client.ClientServerCommunication;
import MainClasses.CreditCard;
import StaticMethods.Tokenization;
import StaticMethods.Validation;
import Server.Session;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author emo
 */
public class SessionFrame extends javax.swing.JFrame {
    private ClientServerCommunication communication;
    Session session;
    /**
     * Creates new form SessionFrame
     */
    public SessionFrame() {
        initComponents();
    }
    public SessionFrame(Session session,ClientServerCommunication comm) {
        this();
        this.session = session;
        communication = comm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        pnlMainPanel = new javax.swing.JPanel();
        txtCreditCard = new javax.swing.JTextField();
        txtToken = new javax.swing.JTextField();
        lblCreditCard = new javax.swing.JLabel();
        lblToken = new javax.swing.JLabel();
        btnTokenize = new javax.swing.JButton();
        btnExportCards = new javax.swing.JButton();
        btnUntokenize = new javax.swing.JButton();
        txtExportToken = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTokenActionPerformed(evt);
            }
        });

        lblCreditCard.setText("Credit Card Number:");

        lblToken.setText("                    Token:");

        btnTokenize.setText("Tokenize&Register");
        btnTokenize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokenizeActionPerformed(evt);
            }
        });

        btnExportCards.setText("Export by Credit Cards");
        btnExportCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportCardsActionPerformed(evt);
            }
        });

        btnUntokenize.setText("Untokenize");
        btnUntokenize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUntokenizeActionPerformed(evt);
            }
        });

        txtExportToken.setText("Export By Tokens");
        txtExportToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExportTokenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainPanelLayout = new javax.swing.GroupLayout(pnlMainPanel);
        pnlMainPanel.setLayout(pnlMainPanelLayout);
        pnlMainPanelLayout.setHorizontalGroup(
            pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainPanelLayout.createSequentialGroup()
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUntokenize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtExportToken, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTokenize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnExportCards, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                            .addGroup(pnlMainPanelLayout.createSequentialGroup()
                                .addComponent(lblCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCreditCard, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txtToken)))))
                    .addComponent(lblToken, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        pnlMainPanelLayout.setVerticalGroup(
            pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblToken, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUntokenize, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnTokenize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExportCards, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txtExportToken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        txtCreditCard.getAccessibleContext().setAccessibleName("txtCreditCard");
        txtToken.getAccessibleContext().setAccessibleName("txtToken");
        lblCreditCard.getAccessibleContext().setAccessibleName("lblCreditCard");
        lblToken.getAccessibleContext().setAccessibleName("lblToken");
        btnTokenize.getAccessibleContext().setAccessibleName("btnTokenize");
        btnExportCards.getAccessibleContext().setAccessibleName("btnExportCards");
        btnUntokenize.getAccessibleContext().setAccessibleName("btnUntokenize");
        txtExportToken.getAccessibleContext().setAccessibleName("txtExportToken");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlMainPanel.getAccessibleContext().setAccessibleName("pnlMainPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTokenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTokenActionPerformed

    private void btnTokenizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokenizeActionPerformed
        // TODO add your handling code here:
        String cardIdString = txtCreditCard.getText();
        String token = "";
        if(Validation.validateCreditCard(cardIdString)){
            token = Tokenization.tokenize(cardIdString);
            txtToken.setText(token);
            CreditCard card = new CreditCard(cardIdString, token);
            communication.sendMessage(card, "Tokenize");
        }
        else{
            JOptionPane.showMessageDialog(null, "Not a valid credit card number");
        }


        
        
    }//GEN-LAST:event_btnTokenizeActionPerformed

    private void btnExportCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportCardsActionPerformed
        // TODO add your handling code here:
        communication.sendMessage(session, "Export By Credit Card");
    }//GEN-LAST:event_btnExportCardsActionPerformed

    private void btnUntokenizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUntokenizeActionPerformed
        // TODO add your handling code here:
        String token = txtToken.getText();
        communication.sendMessage(token, "Untokenize");
        String card = "";
        
        try {
            card = (String) communication.recieveObject();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SessionFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtCreditCard.setText(card);
        
    }//GEN-LAST:event_btnUntokenizeActionPerformed

    private void txtExportTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExportTokenActionPerformed
        // TODO add your handling code here:
        communication.sendMessage(session, "Export By Tokens");
    }//GEN-LAST:event_txtExportTokenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SessionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SessionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SessionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SessionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SessionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportCards;
    private javax.swing.JButton btnTokenize;
    private javax.swing.JButton btnUntokenize;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblCreditCard;
    private javax.swing.JLabel lblToken;
    private javax.swing.JPanel pnlMainPanel;
    private javax.swing.JTextField txtCreditCard;
    private javax.swing.JButton txtExportToken;
    private javax.swing.JTextField txtToken;
    // End of variables declaration//GEN-END:variables
}
